// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AcademicYearController from "./academic_year_controller"
application.register("academic-year", AcademicYearController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
